In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import seaborn as sns



In [2]:
# loading data
data = load_iris()

In [8]:
X=data.data
X


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [9]:
y=data.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)


In [11]:
scaler=StandardScaler()

In [21]:
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)
model=Sequential()
model.add(Dense(64,input_shape=(X_train.shape[1],),activation='relu'))
model.add(Dense(32,activation='relu'))
model.add(Dense(3,activation='softmax'))
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])


In [22]:
model.fit(X_train,y_train,epochs=100,batch_size=32,validation_split=0.2)

Epoch 1/100
3/3 [==============================] - 1s 117ms/step - loss: 1.0150 - accuracy: 0.6250 - val_loss: 1.0452 - val_accuracy: 0.5000
Epoch 2/100
3/3 [==============================] - 0s 16ms/step - loss: 0.9460 - accuracy: 0.6875 - val_loss: 0.9780 - val_accuracy: 0.5417
Epoch 3/100
3/3 [==============================] - 0s 16ms/step - loss: 0.8847 - accuracy: 0.7188 - val_loss: 0.9145 - val_accuracy: 0.6667
Epoch 4/100
3/3 [==============================] - 0s 16ms/step - loss: 0.8285 - accuracy: 0.7708 - val_loss: 0.8564 - val_accuracy: 0.7500
Epoch 5/100
3/3 [==============================] - 0s 16ms/step - loss: 0.7754 - accuracy: 0.8021 - val_loss: 0.8054 - val_accuracy: 0.8333
Epoch 6/100
3/3 [==============================] - 0s 16ms/step - loss: 0.7284 - accuracy: 0.8125 - val_loss: 0.7586 - val_accuracy: 0.8333
Epoch 7/100
3/3 [==============================] - 0s 16ms/step - loss: 0.6824 - accuracy: 0.8229 - val_loss: 0.7164 - val_accuracy: 0.8333
Epoch 8/100
3/3 [==

3/3 [==============================] - 0s 16ms/step - loss: 0.1344 - accuracy: 0.9479 - val_loss: 0.2110 - val_accuracy: 0.9583
Epoch 60/100
3/3 [==============================] - 0s 8ms/step - loss: 0.1315 - accuracy: 0.9479 - val_loss: 0.2115 - val_accuracy: 0.9167
Epoch 61/100
3/3 [==============================] - 0s 8ms/step - loss: 0.1277 - accuracy: 0.9479 - val_loss: 0.2097 - val_accuracy: 0.9167
Epoch 62/100
3/3 [==============================] - 0s 8ms/step - loss: 0.1249 - accuracy: 0.9479 - val_loss: 0.2076 - val_accuracy: 0.9167
Epoch 63/100
3/3 [==============================] - 0s 16ms/step - loss: 0.1218 - accuracy: 0.9479 - val_loss: 0.2056 - val_accuracy: 0.9167
Epoch 64/100
3/3 [==============================] - 0s 16ms/step - loss: 0.1188 - accuracy: 0.9479 - val_loss: 0.2025 - val_accuracy: 0.9167
Epoch 65/100
3/3 [==============================] - 0s 16ms/step - loss: 0.1169 - accuracy: 0.9479 - val_loss: 0.2041 - val_accuracy: 0.9167
Epoch 66/100
3/3 [===========

In [23]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_16 (Dense)            (None, 64)                320       
                                                                 
 dense_17 (Dense)            (None, 32)                2080      
                                                                 
 dense_18 (Dense)            (None, 3)                 99        
                                                                 
Total params: 2,499
Trainable params: 2,499
Non-trainable params: 0
_________________________________________________________________


In [24]:
feature_extractor=Sequential(model.layers[:-1])
train_feature=feature_extractor.predict(X_train)

4/4 [==============================] - 0s 0s/step


In [25]:
test_feature=feature_extractor.predict(X_test)

1/1 [==============================] - 0s 32ms/step


In [26]:
test_feature

array([[7.37693071e-01, 8.37623596e-01, 0.00000000e+00, 2.27958113e-02,
        6.22422040e-01, 0.00000000e+00, 0.00000000e+00, 8.05046678e-01,
        1.07653546e+00, 8.79406512e-01, 9.84711766e-01, 0.00000000e+00,
        0.00000000e+00, 2.50891089e-01, 6.05898201e-01, 1.86895683e-01,
        8.89547288e-01, 0.00000000e+00, 2.85571992e-01, 0.00000000e+00,
        5.79223394e-01, 0.00000000e+00, 5.17117798e-01, 0.00000000e+00,
        9.56920266e-01, 0.00000000e+00, 1.05142760e+00, 0.00000000e+00,
        4.35933441e-01, 3.86348218e-01, 4.94610250e-01, 0.00000000e+00],
       [2.44656131e-01, 3.06643903e-01, 1.68724251e+00, 1.18244660e+00,
        0.00000000e+00, 8.79019678e-01, 0.00000000e+00, 6.32089376e-02,
        0.00000000e+00, 5.64780951e-01, 0.00000000e+00, 1.59956098e+00,
        0.00000000e+00, 7.78869689e-02, 2.28382540e+00, 4.50405777e-02,
        3.44555557e-01, 0.00000000e+00, 1.40018797e+00, 1.94545591e+00,
        2.11379766e+00, 0.00000000e+00, 0.00000000e+00, 1.42539

In [27]:
train_feature

array([[0.0000000e+00, 4.4336438e-01, 2.1892560e+00, ..., 1.4367390e-01,
        0.0000000e+00, 1.3723382e+00],
       [7.0353515e-02, 0.0000000e+00, 2.1283619e+00, ..., 0.0000000e+00,
        0.0000000e+00, 5.9164697e-01],
       [9.7844446e-01, 9.9722016e-01, 2.4101920e-02, ..., 3.7455139e-01,
        4.9811876e-01, 1.7993711e-03],
       ...,
       [2.1372047e-01, 2.0395526e-01, 1.9725084e+00, ..., 0.0000000e+00,
        0.0000000e+00, 5.5662233e-01],
       [6.8533850e-01, 1.2032689e+00, 0.0000000e+00, ..., 4.0834728e-01,
        2.3732400e-01, 5.0828647e-02],
       [5.1421952e-01, 1.6115002e-01, 6.0870081e-01, ..., 0.0000000e+00,
        1.8823090e+00, 1.1662263e+00]], dtype=float32)

In [28]:
#normalize
scaler=StandardScaler()

In [29]:
X_TR=scaler.fit_transform()
X_TT=scaler.transform(X_test)

In [31]:
from sklearn.svm import SVC

In [37]:
svm_m=SVC(kernel='linear')

In [38]:
svm_m.fit(X_TR,y_train)

SVC(kernel='linear')

In [39]:
predicted=svm_m.predict(X_TT)

In [40]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [41]:
accuracy_score(y_test,predicted)

0.9666666666666667

In [42]:
confusion_matrix(y_test,predicted)

array([[10,  0,  0],
       [ 0,  8,  1],
       [ 0,  0, 11]], dtype=int64)